### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN error when obtaining Intel CA certificate in Quick Setup

### ISSUE THREAD

**Issue by hatena75** [intel/SGX-TDX-DCAP-QuoteVerificationService#9]
Hello,

Following Quick Setup in README, QVS and SSS containers were started. Also, all tests were successful in doing so. However, when I access the API for verification with the following curl command, it returns a 500 error.
`curl  -H "Content-Type: application/json" -d '@example.json' --cacert ./configuration-default/certificates/qvs-cert.pem -k https://localhost:8799/attestation/sgx/dcap/v1/report -v`

Looking at the details with the docker logs command, we found the following error log.
```
[INFO] [QuoteVerificationService requestHandler.js:106] [hostname:*** pid:1] [reqId=81d78946066945ec8e2f61fb569d8ec5] Sending request to: https://certificates.trustedservices.intel.com:443/IntelSGXRootCA.der
[ERROR] [QuoteVerificationService requestHandler.js:136] [hostname:*** pid:1] [reqId=81d78946066945ec8e2f61fb569d8ec5] Error while trying to GET https://certificates.trustedservices.intel.com:443/IntelSGXRootCA.der: {"details":{"code":"SELF_SIGNED_CERT_IN_CHAIN","stack":"Error: self-signed certificate in certificate chain\n    at AxiosError.from (/QVS/src/node_modules/axios/dist/node/axios.cjs:837:14)\n    at RedirectableRequest.handleRequestError (/QVS/src/node_modules/axios/dist/node/axios.cjs:3087:25)\n    at RedirectableRequest.emit (node:events:530:35)\n    at eventHandlers.<computed> (/QVS/src/node_modules/follow-redirects/index.js:38:24)\n    at ClientRequest.emit (node:events:518:28)\n    at TLSSocket.socketErrorListener (node:_http_client:495:9)\n    at TLSSocket.emit (node:events:518:28)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (/QVS/src/node_modules/axios/dist/node/axios.cjs:3877:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async nodeRequest (/QVS/src/common/nodeRequestHandler.js:88:26)\n    at async RequestHandler.sendRequest (/QVS/src/common/requestHandler.js:109:25)"},"name":"Error","message":"self-signed certificate in certificate chain","stack":"Error: self-signed certificate in certificate chain\n    at RequestHandler.sendRequest (/QVS/src/common/requestHandler.js:134:55)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
[WARN] [QuoteVerificationService requestHandler.js:134] [hostname:*** pid:1] [reqId=81d78946066945ec8e2f61fb569d8ec5] RuntimeError: self-signed certificate in certificate chain |     at RequestHandler.sendRequest (/QVS/src/common/requestHandler.js:134:55) |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { |   details: { |     code: 'SELF_SIGNED_CERT_IN_CHAIN', |     stack: 'Error: self-signed certificate in certificate chain\n' + |       '    at AxiosError.from (/QVS/src/node_modules/axios/dist/node/axios.cjs:837:14)\n' + |       '    at RedirectableRequest.handleRequestError (/QVS/src/node_modules/axios/dist/node/axios.cjs:3087:25)\n' + |       '    at RedirectableRequest.emit (node:events:530:35)\n' + |       '    at eventHandlers.<computed> (/QVS/src/node_modules/follow-redirects/index.js:38:24)\n' + |       '    at ClientRequest.emit (node:events:518:28)\n' + |       '    at TLSSocket.socketErrorListener (node:_http_client:495:9)\n' + |       '    at TLSSocket.emit (node:events:518:28)\n' + |       '    at emitErrorNT (node:internal/streams/destroy:169:8)\n' + |       '    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n' + |       '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n' + |       '    at Axios.request (/QVS/src/node_modules/axios/dist/node/axios.cjs:3877:41)\n' + |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' + |       '    at async nodeRequest (/QVS/src/common/nodeRequestHandler.js:88:26)\n' + |       '    at async RequestHandler.sendRequest (/QVS/src/common/requestHandler.js:109:25)' |   } | } Request ended with an error. Retrying call host with address: certificates.trustedservices.intel.com:443 ... Attempt number: 1 out of 2`
```

Do you know how I can fix this error?

**Comment by nmwael** [comment]
should'nt you have a self signed ca and then the qvs cert signed by that? That is working for us.

**Comment by hatena75** [comment]
Thanks for the advice.

This error originates from executing the GET method on https://certificates.trustedservices.intel.com:443/IntelSGXRootCA.der. Thus, it was not a problem with QVS's own certificates.

It is not a radical solution, but my problem was avoided by disabling the certificate check.

src/common/RestClient.js
```
prepareOptions(type, certFile, keyFile, caCertDirectories) {
        ...
        const httpsAgentOptions = {
            ...agentOptions,
            ca,
            requestCert: false, //type === tlsType.MTLS,
            maxVersion:  tlsType.MAX_SECURE_PROTOCOL,
            minVersion:  tlsType.MIN_SECURE_PROTOCOL,
            ciphers:     tlsType.CIPHERS,
            servername:  this.cfg.servername,
            rejectUnauthorized: false,
        };
        ...
}
```
